---
title: "Regulation Comparison of Repressilator"
author: "Aidan Tillman"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(sRACIPE)
library(ggplot2)
library(tidyr)
library(dplyr)
```

## Introduction

```{r message=FALSE, warning=FALSE,}
repressilator_tf <- read.table(file.path("../topos",paste0("repressilator_tf",".tpo")), header=T)
repressilator_pd <- read.table(file.path("../topos",paste0("repressilator_pd",".tpo")), header=T)
```


```{r eval=FALSE}
repTFSet <- sracipeSimulate(circuit = repressilator_tf, numModels = 1000, nIC = 200,
                            limitcycles = TRUE, numConvergenceIter = 35, 
                            integrateStepSize = 0.02, maxLCs = 1)
repPDSet <- sracipeSimulate(circuit = repressilator_pd, numModels = 1000, nIC = 200,
                            limitcycles = TRUE, numConvergenceIter = 35, 
                            integrateStepSize = 0.02, maxLCs = 1, foldChangeMinDeg = 1,
                            foldChangeMaxDeg = 100)
```

```{r}
load(file.path("../regCompData",paste0("repTFSet",".RDA")))
load(file.path("../regCompData",paste0("repPDSet",".RDA")))

```

## Comparison of State distributions

```{r}
rep_tf_SS <- sracipeUniqueStates(repTFSet)
rep_pd_SS <- sracipeUniqueStates(repPDSet)
```


```{r}
rep_tf_SS <- Filter(function(x) nrow(x) > 0 && ncol(x) > 0, rep_tf_SS)
rep_tf_SS <- t(do.call(cbind, rep_tf_SS))

rep_pd_SS <- Filter(function(x) nrow(x) > 0 && ncol(x) > 0, rep_pd_SS)
rep_pd_SS <- t(do.call(cbind, rep_pd_SS))
```


```{r}
tmpMeans <- rowMeans(t(log2(1+rep_tf_SS)))
tmpSds <- apply(t(log2(1+rep_tf_SS)),1,sd)
tf_SS_norm <- log2(1+rep_tf_SS)
tf_SS_norm <- sweep(tf_SS_norm, 2, tmpMeans, FUN = "-") # scale
tf_SS_norm <- sweep(tf_SS_norm, 2, tmpSds, FUN = "/") # scale

pd_SS_norm <- log2(1+rep_pd_SS) # Log transform
pd_SS_norm <- sweep(pd_SS_norm, 2, tmpMeans, FUN = "-") # scale
pd_SS_norm <- sweep(pd_SS_norm, 2, tmpSds, FUN = "/") # scale
```


```{r}
pca_tf <- prcomp(tf_SS_norm)
pca_pd <- scale(pd_SS_norm, pca_tf$center, pca_tf$scale) %*% pca_tf$rotation
```

```{r}
k_use <- 3
dist_mat_tf <- dist(pca_tf$x)
hc_tf <- hclust(dist_mat_tf, method = "ward.D2")
cluster_labels_tf <- cutree(hc_tf, k = k_use)

dist_mat_pd <- dist(pca_pd)
hc_pd <- hclust(dist_mat_pd, method = "ward.D2")
cluster_labels_pd <- cutree(hc_pd, k = k_use)

```

```{r echo=FALSE}
pc1_weight <- round(100*summary(pca_tf)$importance[2,1],2)
pc2_weight <- round(100*summary(pca_tf)$importance[2,2],2)
plot_xlab <- paste("PC1 (",pc1_weight,"%)",sep="")
plot_ylab <- paste("PC2 (",pc2_weight,"%)",sep="")

image_tf <- ggplot(pca_tf$x, aes(x=PC1, y=PC2, color=as.factor(cluster_labels_tf))) +
  geom_point(size=2) +
  scale_color_manual(values=c("blue", "red", "green")) +
  xlab(plot_xlab) +
  ylab(plot_ylab) +
  xlim(-4,4) + 
  ylim(-4,4) +
  labs(color="Cluster") + 
  ggtitle("Repressilator TF") +
  theme(axis.line = element_line(linewidth = 1, color = "black"), 
        axis.ticks = element_line(linewidth = 1, color="black"),
        panel.background = element_rect("white"),
        plot.background = element_rect("white"),
        axis.title = element_text(size=28),
        axis.text = element_text(size=24),
        legend.title = element_text(size=18),
        legend.text = element_text(size=14),
        plot.title = element_text(size = 22, hjust = 0.5))
image_tf


image_pd <- ggplot(pca_pd, aes(x=PC1, y=PC2, color=as.factor(cluster_labels_pd))) +
  geom_point(size=2) +
  scale_color_manual(values=c("blue", "red", "green")) +
  xlab(plot_xlab) +
  ylab(plot_ylab) +
  xlim(-4,4) + 
  ylim(-4,4) +
  labs(color="Cluster") + 
  ggtitle("Repressilator PD") +
  theme(axis.line = element_line(linewidth = 1, color = "black"), 
        axis.ticks = element_line(linewidth = 1, color="black"),
        panel.background = element_rect("white"),
        plot.background = element_rect("white"),
        axis.title = element_text(size=28),
        axis.text = element_text(size=24),
        legend.title = element_text(size=18),
        legend.text = element_text(size=14),
        plot.title = element_text(size = 22, hjust = 0.5))
image_pd
```

## Dynamical Mode distribution

```{r}

rep_tfStateCounts <- repTFSet@metadata[["uniqueStateCounts"]][["UniqueStableStateNo"]]
rep_pdStateCounts <- repPDSet@metadata[["uniqueStateCounts"]][["UniqueStableStateNo"]]

LC_tf <- repTFSet@metadata[["LCData"]]
LC_pd <- repPDSet@metadata[["LCData"]]

tf_LCbool <- integer(1000)
tf_LCbool[LC_tf[[1]]] <- 1

pd_LCbool <- integer(1000)
pd_LCbool[LC_pd[[1]]] <- 1
```

```{r echo=FALSE}


state_pd_plot <- data.frame(
  setup= "PD",
  stateCount = rep_pdStateCounts,
  group = pd_LCbool
)
state_tf_plot <- data.frame(
    setup= "TF",
    stateCount = rep_tfStateCounts,
  group = tf_LCbool
)

state_plot <- bind_rows(state_pd_plot, state_tf_plot)

state_plot <- state_plot %>% filter(stateCount %in% 0:1)

state_summary <- state_plot %>%
  group_by(setup, group, stateCount) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(setup) %>%
  mutate(prop = count / sum(count))

plot_group <- function(g) {
  ggplot(dplyr::filter(state_summary, group == g),
         aes(x = factor(stateCount), y = prop, fill = setup)) +
    geom_col(position = "dodge") +
    scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
    labs(
      x = "State Count",
      y = "Proportion",
      fill = "Setup",
      title = paste("Group", g)
    ) +
    theme_minimal()  +
    theme(
      axis.text.x = element_text(size = 16),
      axis.text.y = element_text(size = 16, face="bold"),
      axis.title = element_text(size = 16))
}

plot_group0 <- plot_group(0)
plot_group1 <- plot_group(1)

# Example: print them
print(plot_group0)
print(plot_group1)

```


## Comparison of Limit Cycle Properties


```{r}

tf_periods <- LC_tf %>%
  distinct(model = LC_tf[[1]], period = LC_tf[[3]]) %>%
  pull(period)
pd_periods <- LC_pd %>%
  distinct(model = LC_pd[[1]], period = LC_pd[[3]]) %>%
  pull(period)


PDMeanPeriod <- mean(pd_periods)*0.01
TFMeanPeriod <- mean(tf_periods)*0.01

PDSTDPeriod <- sd(pd_periods)*0.01
TFSTDPeriod <- sd(tf_periods)*0.01

stats_cc <- data.frame(
  group = c("PD Model", "TF Model"),
  mean  = c(PDMeanPeriod, TFMeanPeriod),
  sd    = c(PDSTDPeriod, TFSTDPeriod)
)

image_period <- ggplot(stats_cc, aes(x = group, y = mean)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd), width = 0.2) +
  ylab("Unit Time") +
  ylim(0,30) +
  theme_minimal()

image_period

```


